export const tier1MockCompanies = [
    {
        _id: 't1-001',
        name: 'Global Tech Solutions',
        email: 'info@globaltech.com',
        role: 'Tier 1',
        isActive: true,
        createdAt: new Date('2023-01-15').toISOString(),
        updatedAt: new Date('2023-01-15').toISOString(),
        details: {
            companyName: 'Global Tech Solutions',
            businessType: 'Technology',
            industryType: 'IT',
            companyType: 'Public',
            parentCompanyName: 'Global Holdings Corp',
            numberOfEmployees: '5000',
            numberOfBranches: '25',
            headOfficeLocation: 'San Francisco, CA',
            officialCompanyEmail: 'corporate@globaltech.com',
            companyContactNumber: '+1-555-0101',
            companyWebsite: 'https://globaltech.com',
            companyPanNumber: 'ABCDE1234F',
            companyCinNumber: 'L12345KA2010PLC054321',
            gstNumber: '22AAAAA0000A1Z5',
            taxNumber: 'TAX-987654321',
            registrationDate: '2010-05-20',
            expiryDate: '2030-05-20',
            annualRevenue: '1000000000',
            paidUpCapital: '50000000',
            netWorth: '200000000',
            lastYearTurnover: '950000000',
            complianceOfficerName: 'John Doe',
            complianceOfficerEmail: 'john.doe@globaltech.com',
            complianceOfficerPhone: '+1-555-0202',
            auditFirmName: 'Price & Waters',
            lastAuditDate: '2023-12-01'
        }
    },
    {
        _id: 't1-002',
        name: 'Industrial Manufacturing Inc.',
        email: 'contact@industrialmfg.com',
        role: 'Tier 1',
        isActive: true,
        createdAt: new Date('2022-11-20').toISOString(),
        details: {
            companyName: 'Industrial Manufacturing Inc.',
            businessType: 'Manufacturing',
            industryType: 'Manufacturing',
            companyType: 'Private',
            parentCompanyName: 'Heavy Industries Group',
            numberOfEmployees: '2500',
            numberOfBranches: '12',
            headOfficeLocation: 'Chicago, IL',
            officialCompanyEmail: 'ops@industrialmfg.com',
            companyContactNumber: '+1-555-0303',
            companyWebsite: 'https://industrialmfg.com',
            companyPanNumber: 'FGHIJ5678K',
            companyCinNumber: 'U56789IL2005PTC067890',
            gstNumber: '17BBBBB1111B2Y6',
            taxNumber: 'TAX-123456789',
            registrationDate: '2005-09-12',
            expiryDate: '2025-09-12',
            annualRevenue: '500000000',
            paidUpCapital: '30000000',
            netWorth: '120000000',
            lastYearTurnover: '480000000',
            complianceOfficerName: 'Jane Smith',
            complianceOfficerEmail: 'jane.smith@industrialmfg.com',
            complianceOfficerPhone: '+1-555-0404',
            auditFirmName: 'Everest Audit Co.',
            lastAuditDate: '2023-10-15'
        }
    },
    {
        _id: 't1-003',
        name: 'Future Financials Ltd.',
        email: 'hello@futurefinancials.com',
        role: 'Tier 1',
        isActive: true,
        createdAt: new Date('2024-02-05').toISOString(),
        details: {
            companyName: 'Future Financials Ltd.',
            businessType: 'Services',
            industryType: 'Finance',
            companyType: 'Public',
            parentCompanyName: 'Future Wealth Group',
            numberOfEmployees: '1200',
            numberOfBranches: '8',
            headOfficeLocation: 'New York, NY',
            officialCompanyEmail: 'legal@futurefinancials.com',
            companyContactNumber: '+1-555-0505',
            companyWebsite: 'https://futurefinancials.com',
            companyPanNumber: 'KLMNO9012P',
            companyCinNumber: 'L90123NY2015PLC090123',
            gstNumber: '36CCCCC2222C3X7',
            taxNumber: 'TAX-445566778',
            registrationDate: '2015-03-30',
            expiryDate: '2035-03-30',
            annualRevenue: '750000000',
            paidUpCapital: '40000000',
            netWorth: '150000000',
            lastYearTurnover: '700000000',
            complianceOfficerName: 'Robert Brown',
            complianceOfficerEmail: 'robert.brown@futurefinancials.com',
            complianceOfficerPhone: '+1-555-0606',
            auditFirmName: 'Guardian Audits',
            lastAuditDate: '2023-11-20'
        }
    }
];
